#:kivy 1.0

<Alert>:
    ellipsis_options: {'color':(1,0.5,0.5,1),'underline':True}
    shorten: True
    markup: True
    shorten_from: 'right'
    size_hint: 0.4, 0.5
    pos_hint: {"center_x": 0.50, "center_y": 0.8}
    halign: 'center'
    valign: 'middle'
    canvas.before:
        Rectangle:
            id: 'Alert-'+str(self.message)
            size: self.size
            pos: self.pos
            source: 'static/imgs/Alerts/FordWarning.png'
