name: Build Kivy App

on:
  push:
    branches:
      - automate-iso-release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libsdl2-dev libsdl2-image-dev \
              libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
              libavformat-dev libavcodec-dev zlib1g-dev gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good
          pip install --upgrade pip setuptools wheel
          pip install kivy pyinstaller

      - name: Build Kivy Binary
        run: |
          pyinstaller --onefile --windowed main.py
          mv dist/main kivy-binary

      - name: Upload Kivy Binary
        uses: actions/upload-artifact@v3
        with:
          name: kivy-binary
          path: kivy-binary
