name: Build SvelteKit App

on:
  push:
    branches:
      - automate-iso-release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd sveltekit-app
          npm install

      - name: Build SvelteKit App
        run: |
          cd sveltekit-app
          npm run build
          cp -r build ../sveltekit-build

      - name: Upload SvelteKit Build
        uses: actions/upload-artifact@v4
        with:
          name: sveltekit-build
          path: sveltekit-build/
