name: Build Custom Image

on:
  workflow_run:
    workflows:
      - Build Kivy App
      - Build SvelteKit App
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Kivy Binary
        uses: actions/download-artifact@v3
        with:
          name: kivy-binary
          path: kivy-binary/

      - name: Download SvelteKit Build
        uses: actions/download-artifact@v3
        with:
          name: sveltekit-build
          path: sveltekit-build/

      - name: Debug Downloaded Artifacts
        run: |
          echo "Kivy Binary:"
          ls -la kivy-binary
          echo "SvelteKit Build:"
          ls -la sveltekit-build

      - name: Customize Raspbian Image
        run: |
          chmod +x ./scripts/customize_raspbian.sh
          ./scripts/customize_raspbian.sh kivy-binary/ sveltekit-build/

      - name: Compress the Image
        run: |
          mkdir -p dist
          gzip -c custom-raspbian-lite.img > dist/custom-raspbian-lite.img.gz

      - name: Upload Compressed Image
        uses: actions/upload-artifact@v3
        with:
          name: raspbian-image
          path: dist/custom-raspbian-lite.img.gz
